/**
 * PHP + HTML landing page template generator.
 * NOTE: This file is intentionally excluded from Tailwind v4 content scanning
 * via `@source not` in globals.css — do NOT add Tailwind class names here.
 */

export type CarouselCategory = "deals" | "family" | "group" | "treks";

export interface PackageCard {
  id: string;
  category: CarouselCategory;
  title: string;
  image: string;
  duration: string;
  price: number;
  badge: string;
  highlights: string[];
  fromCatalogue: boolean;
  catalogueId?: string;
}

export interface TrustStat { icon: string; value: string; label: string; }
export interface WhyCard { icon: string; title: string; description: string; }
export interface FaqItem { id: string; question: string; answer: string; }
export interface CategoryLabel { key: CarouselCategory; label: string; }

export interface LandingPageData {
  pageTitle: string;
  metaDescription: string;
  destination: string;
  pixelId: string;
  logoUrl: string;
  waNumber: string;
  callNumber: string;
  heroImage: string;
  heroBadge: string;
  heroHeadline: string;
  heroSubheadline: string;
  heroSlotYear: string;
  trustStats: TrustStat[];
  categoryLabels: CategoryLabel[];
  packages: PackageCard[];
  whyTitle: string;
  whySubtitle: string;
  whyCards: WhyCard[];
  faqs: FaqItem[];
}

const CAT_KEYS: CarouselCategory[] = ["deals", "family", "group", "treks"];

export function generatePhpContent(d: LandingPageData): string {
  const catLabel = (key: CarouselCategory) =>
    d.categoryLabels.find(c => c.key === key)?.label ?? key;
  const pkgsByCat = (cat: CarouselCategory) =>
    d.packages.filter(p => p.category === cat);
  const cardJs = (p: PackageCard) =>
    `{title:${JSON.stringify(p.title)},image:${JSON.stringify(p.image)},duration:${JSON.stringify(p.duration)},price:${p.price},badge:${JSON.stringify(p.badge)},highlights:${JSON.stringify(p.highlights)}}`;
  const pkgsJs = CAT_KEYS
    .map(c => `    ${c}: [${pkgsByCat(c).map(cardJs).join(",")}]`)
    .join(",\n");

  // The bg-image inline style is built from parts so no static url() literal exists
  // that would confuse bundlers or CSS scanners during build time.
  const bgImgParts = ["background-image:", "url('", d.heroImage, "')"];
  const heroBgStyle = bgImgParts.join("");

  return [
    `<?php`,
    `declare(strict_types=1);`,
    `/**`,
    ` * ${d.destination.toUpperCase()} landing — generated by The Vacation Voice portal.`,
    ` * Set secrets via env: TVV_WEBHOOK_URL, TVV_WEBHOOK_BEARER, TVV_META_PIXEL_ID, TVV_META_ACCESS_TOKEN`,
    ` */`,
    `$TVV_WEBHOOK_URL    = getenv('TVV_WEBHOOK_URL') ?: 'https://automationx.thevacationvoice.com/webhook/040d57e7-d351-4508-8f1d-9a89b49de53a';`,
    `$TVV_WEBHOOK_BEARER = getenv('TVV_WEBHOOK_BEARER') ?: '480|J6zatmCdITchU40z0UwC61qd8fuToxg2WldtNjg3c5ee0d44';`,
    `$TVV_META_PIXEL_ID  = getenv('TVV_META_PIXEL_ID') ?: '${d.pixelId}';`,
    `$TVV_META_ACCESS_TOKEN = getenv('TVV_META_ACCESS_TOKEN') ?: '';`,
    `$TVV_META_API_VERSION  = 'v18.0';`,
    ``,
    `function tvv_client_ip() {`,
    `  if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {`,
    `    $ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);`,
    `    return trim($ips[0]);`,
    `  }`,
    `  return $_SERVER['REMOTE_ADDR'] ?? '';`,
    `}`,
    ``,
    `if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_GET['action'] ?? '') === 'lead') {`,
    `  header('Content-Type: application/json; charset=utf-8');`,
    `  $raw  = file_get_contents('php://input');`,
    `  $data = json_decode($raw, true);`,
    `  if (!is_array($data)) { http_response_code(400); echo json_encode(['ok'=>false,'error'=>'Invalid JSON']); exit; }`,
    `  // TODO: copy webhook + Meta CAPI logic from base template here`,
    `  echo json_encode(['ok'=>true]);`,
    `  exit;`,
    `}`,
    `$TVV_PIXEL_ESC = htmlspecialchars($TVV_META_PIXEL_ID, ENT_QUOTES, 'UTF-8');`,
    `?>`,
    `<!DOCTYPE html>`,
    `<html lang="en">`,
    `<head>`,
    `  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
    `  <title>${d.pageTitle}</title>`,
    `  <meta name="description" content="${d.metaDescription}" />`,
    `  <link rel="preconnect" href="https://fonts.googleapis.com" />`,
    `  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet" />`,
    `  <script src="https://cdn.tailwindcss.com"></script>`,
    `  <script>tailwind.config={theme:{extend:{colors:{brand:{DEFAULT:'#0066cc',700:'#004d99'},wa:'#25d366'},fontFamily:{sans:['Poppins','system-ui','sans-serif']}}}};</script>`,
    `</head>`,
    `<body class="font-sans text-slate-700 antialiased bg-white">`,
    ``,
    `<header class="sticky top-0 z-50 bg-white border-b border-slate-100 shadow-sm">`,
    `  <div class="mx-auto flex max-w-6xl items-center justify-between px-5 py-3 lg:px-8">`,
    `    <a href="#"><img src="${d.logoUrl}" alt="The Vacation Voice" class="h-8 w-auto md:h-9" /></a>`,
    `    <nav class="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex">`,
    `      <a href="#">Home</a><a href="#packages">Packages</a><a href="#whyus">Why Us</a><a href="#faq">FAQs</a>`,
    `      <a href="#enquiry-form" class="rounded-lg bg-brand px-4 py-2 text-white font-semibold hover:bg-brand-700">Submit Enquiry</a>`,
    `    </nav>`,
    `  </div>`,
    `</header>`,
    ``,
    `<section class="relative overflow-hidden bg-slate-900">`,
    `  <div class="absolute inset-0 bg-cover bg-center" style="${heroBgStyle}"></div>`,
    `  <div class="absolute inset-0 bg-slate-900/45"></div>`,
    `  <div class="relative mx-auto grid max-w-6xl gap-10 px-4 py-20 md:grid-cols-2 lg:px-8">`,
    `    <div class="flex flex-col justify-center text-white">`,
    `      <span class="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-medium text-white/80">${d.heroBadge}</span>`,
    `      <h1 class="mt-5 text-4xl font-extrabold leading-tight">`,
    `        ${d.heroHeadline.split("\n").join("<br />")}`,
    `        <br /><span class="text-amber-300">Limited Slots ${d.heroSlotYear}</span>`,
    `      </h1>`,
    `      <p class="mt-4 text-lg text-white/80">${d.heroSubheadline}</p>`,
    `      <div class="mt-6 flex flex-wrap gap-3">`,
    `        <a href="https://wa.me/${d.waNumber}" target="_blank" class="inline-flex items-center gap-2 rounded-xl bg-wa px-6 py-3 text-sm font-bold text-white">Get Itinerary on WhatsApp</a>`,
    `        <a href="tel:${d.callNumber}" class="inline-flex items-center gap-2 rounded-xl bg-white/15 border border-white/30 px-6 py-3 text-sm font-bold text-white">Call Now</a>`,
    `      </div>`,
    `      <div class="mt-6 grid grid-cols-2 sm:grid-cols-4 gap-2">`,
    ...d.trustStats.map(s =>
      `        <div class="rounded-lg bg-white/10 px-3 py-2 backdrop-blur-sm text-center border border-white/10"><p class="font-bold text-white text-sm">${s.value}</p><p class="text-xs text-white/60 uppercase tracking-wider mt-0.5">${s.label}</p></div>`
    ),
    `      </div>`,
    `    </div>`,
    `    <div id="enquiry-form" class="rounded-2xl bg-white p-6 shadow-2xl scroll-mt-20">`,
    `      <h2 class="text-lg font-bold text-slate-900 text-center">Please submit your info</h2>`,
    `      <form id="leadForm" class="mt-5" novalidate>`,
    `        <input type="hidden" name="destination" value="${d.destination}" />`,
    `        <div class="space-y-3">`,
    `          <div><label class="block text-xs font-medium text-slate-600 mb-1">Full name *</label><input type="text" name="your-name" required class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-1 focus:ring-brand" /></div>`,
    `          <div><label class="block text-xs font-medium text-slate-600 mb-1">Email *</label><input type="email" name="your-email" required class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-1 focus:ring-brand" /></div>`,
    `          <div><label class="block text-xs font-medium text-slate-600 mb-1">Phone *</label><input type="tel" name="your-phone" required class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-1 focus:ring-brand" /></div>`,
    `          <div class="grid grid-cols-2 gap-3">`,
    `            <div><label class="block text-xs font-medium text-slate-600 mb-1">Budget</label><select name="budget" class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><option value="">Select</option><option>20k-25k</option><option>25k-35k</option><option>35k-45k</option><option>45k+</option></select></div>`,
    `            <div><label class="block text-xs font-medium text-slate-600 mb-1">Nights</label><select name="duration" class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><option value="">Select</option><option>4 Nights</option><option>5 Nights</option><option>6 Nights</option><option>7 Nights</option></select></div>`,
    `          </div>`,
    `        </div>`,
    `        <button type="submit" class="mt-4 w-full rounded-lg bg-brand py-2.5 text-sm font-semibold text-white hover:bg-brand-700">Submit Enquiry</button>`,
    `      </form>`,
    `    </div>`,
    `  </div>`,
    `</section>`,
    ``,
    `<section id="packages" class="py-16 bg-slate-50">`,
    `  <div class="mx-auto max-w-6xl px-5 lg:px-8">`,
    `    <div class="text-center">`,
    `      <p class="text-sm font-semibold uppercase tracking-wider text-brand">Curated with expertise</p>`,
    `      <h2 class="mt-2 text-3xl font-bold text-slate-900">Best Deals</h2>`,
    `    </div>`,
    ...CAT_KEYS.map(cat =>
      `    <div class="mt-10"><h3 class="mb-4 text-base font-semibold text-slate-900">${catLabel(cat)}</h3><div id="carousel-${cat}" class="flex gap-5 overflow-x-auto pb-2"></div></div>`
    ),
    `  </div>`,
    `</section>`,
    ``,
    `<section id="whyus" class="py-16 bg-blue-50">`,
    `  <div class="mx-auto max-w-6xl px-5">`,
    `    <div class="text-center mb-10">`,
    `      <h2 class="text-2xl font-semibold text-slate-900">${d.whyTitle}</h2>`,
    `      <p class="mt-3 text-slate-600">${d.whySubtitle}</p>`,
    `    </div>`,
    `    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-${d.whyCards.length} gap-4">`,
    ...d.whyCards.map(c =>
      `      <div class="bg-white rounded-xl p-6 shadow-sm border-b-4 border-amber-700"><h3 class="font-semibold text-slate-800">${c.title}</h3><p class="mt-2 text-sm text-slate-500">${c.description}</p></div>`
    ),
    `    </div>`,
    `  </div>`,
    `</section>`,
    ``,
    `<section id="faq" class="py-16 bg-white">`,
    `  <div class="mx-auto max-w-3xl px-5">`,
    `    <h2 class="text-2xl font-semibold text-slate-900 text-center mb-8">Frequently Asked Questions</h2>`,
    ...d.faqs.map(faq =>
      `    <details class="border border-slate-200 rounded-xl mb-3 px-5 py-4"><summary class="font-semibold cursor-pointer">${faq.question}</summary><p class="mt-3 text-slate-600 text-sm">${faq.answer}</p></details>`
    ),
    `  </div>`,
    `</section>`,
    ``,
    `<script>`,
    `const PACKAGES = {`,
    pkgsJs,
    `};`,
    `(function() {`,
    `  var cats = ['deals','family','group','treks'];`,
    `  cats.forEach(function(cat) {`,
    `    var el = document.getElementById('carousel-' + cat);`,
    `    if (!el || !PACKAGES[cat] || !PACKAGES[cat].length) { if(el) el.closest('.mt-10').style.display='none'; return; }`,
    `    el.innerHTML = PACKAGES[cat].map(function(p) {`,
    `      return '<div style="min-width:220px" class="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden shrink-0">'`,
    `        + '<div class="relative h-36 bg-slate-200"><img src="' + p.image + '" class="w-full h-full object-cover" alt="' + p.title + '" />'`,
    `        + (p.badge ? '<span class="absolute top-2 left-2 bg-amber-500 text-white text-xs font-bold px-2 py-0.5 rounded-full">' + p.badge + '</span>' : '')`,
    `        + '</div><div class="p-3"><p class="text-sm font-bold text-slate-900 leading-tight">' + p.title + '</p>'`,
    `        + '<div class="mt-2 flex items-center justify-between"><span class="text-xs text-slate-500">' + p.duration + '</span><span class="text-sm font-bold text-blue-600">\\u20B9' + Number(p.price).toLocaleString() + '</span></div>'`,
    `        + (p.highlights && p.highlights.length ? '<div class="mt-1.5 flex flex-wrap gap-1">' + p.highlights.slice(0,2).map(function(h){return '<span class="text-xs bg-blue-50 text-blue-700 px-1.5 py-0.5 rounded">'+h+'</span>';}).join('') + '</div>' : '')`,
    `        + '</div></div>';`,
    `    }).join('');`,
    `  });`,
    `})();`,
    `</script>`,
    `</body>`,
    `</html>`,
  ].join("\n");
}

export function generateHtmlContent(d: LandingPageData): string {
  const full = generatePhpContent(d);
  // Remove everything from the first line up to and including the closing PHP tag
  const closingTag = "?>\n";
  const idx = full.indexOf(closingTag);
  const html = idx !== -1 ? full.slice(idx + closingTag.length) : full;
  return html + "\n<!-- NOTE: Replace form action with your /api/lead endpoint for static hosting -->";
}
