import { randomUUID } from "node:crypto";
import { CATEGORY_KEY_PREFIX, type StorageCategory } from "../types/storage-category";

function purposeSlug(category: StorageCategory): string {
  return category.toLowerCase().replace(/_/g, "-");
}

function extensionFromFileName(fileName: string): string {
  const dot = fileName.lastIndexOf(".");
  if (dot === -1 || dot === fileName.length - 1) return "bin";
  return fileName.slice(dot + 1).toLowerCase();
}

/**
 * docs/18's `{module}/{ownerId}/{purpose}-{uuid}.{ext}` convention — the key
 * itself is the module's only ownership record (there is no `repositories/`
 * folder or new Prisma model for Storage). `ownerId`'s segment is what
 * `extractOwnerIdFromKey` later parses back out for the ownership check,
 * so a key can never be generated without an owner to validate later.
 */
export function generateStorageKey(category: StorageCategory, ownerId: string, fileName: string): string {
  const prefix = CATEGORY_KEY_PREFIX[category];
  const purpose = purposeSlug(category);
  const ext = extensionFromFileName(fileName);
  return `${prefix}/${ownerId}/${purpose}-${randomUUID()}.${ext}`;
}

/** Parses the `ownerId` segment back out of a key generated by `generateStorageKey`. */
export function extractOwnerIdFromKey(category: StorageCategory, key: string): string | null {
  const prefix = CATEGORY_KEY_PREFIX[category];
  if (!key.startsWith(`${prefix}/`)) return null;
  const rest = key.slice(prefix.length + 1);
  const ownerId = rest.split("/")[0];
  return ownerId || null;
}
