"use client";

import { useState, useEffect } from "react";
import { Compass, Plus, Search, MapPin, Clock, X } from "lucide-react";
import { adminApiClient } from "@/lib/admin-api/client";
import { adminEndpoints } from "@/lib/admin-api/endpoints";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AlertModal } from "@/components/layout/AlertModal";

interface Activity {
  id: string;
  name: string;
  location: string;
  duration: string;
  adultPrice: number;
  childPrice: number;
  status: "ACTIVE" | "INACTIVE";
}

export default function ActivitiesPage() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [isSearchMode, setIsSearchMode] = useState(false);
  const [isSearchingLive, setIsSearchingLive] = useState(false);
  const [alertState, setAlertState] = useState({ isOpen: false, message: "" });
  const [searchResults, setSearchResults] = useState<Activity[] | null>(null);
  const [searchParams, setSearchParams] = useState({
    city: "BOM",
    date: new Date().toISOString().split('T')[0]
  });

  const [newActivity, setNewActivity] = useState<Partial<Activity>>({
    name: "",
    location: "Havelock Island",
    duration: "2 Hours",
    adultPrice: 1000,
    childPrice: 500,
    status: "ACTIVE",
  });

  const { data: inventoryData, isLoading: isInventoryLoading } = useQuery({
    queryKey: ["admin", "inventory", "ACTIVITY"],
    queryFn: async () => {
      const res = await adminApiClient.get<any>(adminEndpoints.inventory, { params: { kind: "ACTIVITY", pageSize: 100 } });
      if (!res) return [];
      return res.items.map((item: any) => ({
        id: item.id,
        name: item.title,
        location: item.details?.location || "Unknown",
        duration: item.details?.duration || "Unknown",
        adultPrice: item.details?.adultPrice || 0,
        childPrice: item.details?.childPrice || 0,
        status: item.status,
      })) as Activity[];
    }
  });

  const activities = inventoryData || [];

  const createMutation = useMutation({
    mutationFn: async (activity: Activity) => {
      const payload = {
        kind: "ACTIVITY",
        title: activity.name,
        status: activity.status,
        details: {
          location: activity.location,
          duration: activity.duration,
          adultPrice: activity.adultPrice,
          childPrice: activity.childPrice,
        }
      };
      return adminApiClient.post(adminEndpoints.inventory, payload);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["admin", "inventory", "ACTIVITY"] });
    }
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      return adminApiClient.delete(`${adminEndpoints.inventory}/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["admin", "inventory", "ACTIVITY"] });
    }
  });

  const filteredActivities = activities.filter((a) =>
    a.name.toLowerCase().includes(search.toLowerCase()) ||
    a.location.toLowerCase().includes(search.toLowerCase())
  );

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    const activity: Activity = {
      id: "", // generated by backend
      name: newActivity.name || "",
      location: newActivity.location || "",
      duration: newActivity.duration || "1 Hour",
      adultPrice: Number(newActivity.adultPrice) || 0,
      childPrice: Number(newActivity.childPrice) || 0,
      status: newActivity.status as "ACTIVE" | "INACTIVE" || "ACTIVE",
    };

    await createMutation.mutateAsync(activity);
    setIsModalOpen(false);

    // Reset form
    setNewActivity({
      name: "",
      location: "Havelock Island",
      duration: "2 Hours",
      adultPrice: 1000,
      childPrice: 500,
      status: "ACTIVE",
    });
  };

  const removeActivity = (id: string) => {
    setConfirmDeleteId(id);
  };

  const handleConfirmDelete = async () => {
    if (confirmDeleteId) {
      await deleteMutation.mutateAsync(confirmDeleteId);
      setConfirmDeleteId(null);
    }
  };

  const activeCatalogCount = activities.filter(a => a.status === "ACTIVE").length;
  // Use unique locations as operators count
  const operatorsCount = new Set(activities.map(a => a.location)).size;

  const handleLiveSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSearchingLive(true);
    setSearchResults(null);
    try {
      const data = await adminApiClient.post<{ success: boolean; data?: any; error?: any }>('/api/supplier/search', {
        capability: "ACTIVITIES",
        criteria: {
          capability: "ACTIVITIES",
          cityCode: searchParams.city,
          date: searchParams.date
        }
      });
      if (data && data.success && data.data?.results) {
        const mapped: Activity[] = data.data.results.map((res: any) => ({
          id: res.referenceId || `ACT-${Date.now()}`,
          name: res.activityName || "Unknown Activity",
          location: res.location || searchParams.city,
          duration: res.duration || "2 Hours",
          adultPrice: res.adultPrice || 0,
          childPrice: res.childPrice || 0,
          status: "ACTIVE"
        }));
        setSearchResults(mapped);
      } else {
        setAlertState({ isOpen: true, message: data?.error?.message || "Failed to search activities" });
      }
    } catch (err) {
      setAlertState({ isOpen: true, message: "Network error while searching activities" });
    } finally {
      setIsSearchingLive(false);
    }
  };

  const saveLiveActivity = async (activity: Activity) => {
    if (!activities.find(a => a.name === activity.name)) {
      await createMutation.mutateAsync(activity);
    }
  };

  return (
    <div className="space-y-6 relative">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Activities & Excursions</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Build your excursion catalog, ticket rates, provider payouts, and time-slot limits.
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => {
              setIsSearchMode(!isSearchMode);
              setSearchResults(null);
            }}
            className="flex items-center gap-2 px-4 py-2 bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 font-semibold rounded-md shadow-sm hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
          >
            <Search className="h-4 w-4" />
            {isSearchMode ? "Back to Managed Activities" : "Live API Search"}
          </button>
          <button
            onClick={() => setIsModalOpen(true)}
            className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground font-semibold rounded-md shadow-sm hover:bg-primary-hover transition-colors"
          >
            <Plus className="h-4 w-4" /> Add Activity
          </button>
        </div>
      </div>

      {isSearchMode ? (
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-900 border border-border rounded-xl shadow-sm p-5">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
              <Compass className="h-5 w-5 text-primary" />
              Live Activity Search
            </h2>
            <form onSubmit={handleLiveSearch} className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
              <div className="md:col-span-2">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">City Code</label>
                <div className="relative">
                  <input required type="text" value={searchParams.city} onChange={e => setSearchParams({ ...searchParams, city: e.target.value.toUpperCase() })} className="w-full bg-white border border-slate-300 dark:border-slate-700 rounded-lg pl-9 pr-3 py-2 text-sm font-bold uppercase" />
                  <MapPin className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                </div>
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Date</label>
                <input required type="date" value={searchParams.date} onChange={e => setSearchParams({ ...searchParams, date: e.target.value })} className="w-full bg-white border border-slate-300 dark:border-slate-700 rounded-lg px-3 py-2 text-sm" />
              </div>
              <button type="submit" disabled={isSearchingLive} className="w-full py-2 bg-primary text-primary-foreground font-bold rounded-lg hover:bg-primary-hover transition-colors shadow-sm disabled:opacity-50">
                {isSearchingLive ? "Searching..." : "Search"}
              </button>
            </form>
          </div>

          {searchResults && (
            <div className="space-y-4">
              <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wide">
                API Results ({searchResults.length} activities found)
              </h3>
              <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                {searchResults.map(activity => {
                  const isSaved = activities.some(a => a.id === activity.id);
                  return (
                    <div key={activity.id} className="bg-white dark:bg-slate-900 border border-border rounded-xl p-5 shadow-sm flex flex-col justify-between gap-4">
                      <div>
                        <h4 className="font-bold text-foreground text-lg leading-tight mb-2">{activity.name}</h4>
                        <p className="text-xs text-muted-foreground flex items-center gap-1 mb-1">
                          <MapPin className="h-3 w-3" /> {activity.location}
                        </p>
                        <p className="text-xs text-muted-foreground flex items-center gap-1 mb-3">
                          <Clock className="h-3 w-3" /> {activity.duration}
                        </p>
                      </div>
                      <div className="flex items-center justify-between border-t border-slate-100 dark:border-slate-800 pt-4">
                        <div>
                          <p className="text-xs text-muted-foreground">Adult Rate</p>
                          <p className="text-xl font-black text-primary">₹{activity.adultPrice.toLocaleString()}</p>
                        </div>
                        <button
                          onClick={() => saveLiveActivity(activity)}
                          disabled={isSaved}
                          className={`px-4 py-2 rounded-lg text-sm font-bold transition-colors ${isSaved ? "bg-slate-100 text-slate-400 border border-slate-200" : "bg-emerald-500 hover:bg-emerald-600 text-white"}`}
                        >
                          {isSaved ? "Saved" : "Save"}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      ) : (
        <>
          {/* Grid Summary */}
          <div className="grid gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-50 text-blue-600 rounded-lg">
                  <Compass className="h-6 w-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Catalog Items</p>
                  <h3 className="text-2xl font-bold">{activeCatalogCount} Activities</h3>
                </div>
              </div>
            </div>
            <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-emerald-50 text-emerald-600 rounded-lg">
                  <MapPin className="h-6 w-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Locations Covered</p>
                  <h3 className="text-2xl font-bold">{operatorsCount} Zones</h3>
                </div>
              </div>
            </div>
            <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-purple-50 text-purple-600 rounded-lg">
                  <Clock className="h-6 w-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-muted-foreground">Recent Additions</p>
                  <h3 className="text-2xl font-bold">This Month</h3>
                </div>
              </div>
            </div>
          </div>

          {/* Table Container */}
          <div className="bg-card border border-border rounded-lg shadow-sm overflow-hidden">
            <div className="p-4 border-b border-border flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="relative w-full max-w-sm">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <input
                  type="text"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder="Search by activity name or location..."
                  className="w-full bg-background border border-input rounded-md pl-9 pr-4 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-ring"
                />
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-muted-foreground uppercase bg-slate-50/50 border-b border-border">
                  <tr>
                    <th className="px-6 py-4 font-semibold">Activity ID</th>
                    <th className="px-6 py-4 font-semibold">Activity</th>
                    <th className="px-6 py-4 font-semibold">Location</th>
                    <th className="px-6 py-4 font-semibold">Duration</th>
                    <th className="px-6 py-4 font-semibold">Adult Rate</th>
                    <th className="px-6 py-4 font-semibold">Child Rate</th>
                    <th className="px-6 py-4 font-semibold">Status</th>
                    <th className="px-6 py-4 font-semibold text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {isInventoryLoading ? (
                    <tr>
                      <td colSpan={8} className="px-6 py-8 text-center text-muted-foreground">
                        Loading activities...
                      </td>
                    </tr>
                  ) : filteredActivities.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="px-6 py-8 text-center text-muted-foreground">
                        No activities found matching your search.
                      </td>
                    </tr>
                  ) : (
                    filteredActivities.map((activity) => (
                      <tr key={activity.id} className="hover:bg-muted/50 transition-colors">
                        <td className="px-6 py-4 font-medium text-foreground whitespace-nowrap">
                          {activity.id}
                        </td>
                        <td className="px-6 py-4 font-semibold text-foreground whitespace-nowrap">
                          {activity.name}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-muted-foreground text-xs flex items-center gap-1">
                            <MapPin className="h-3 w-3" />
                            {activity.location}
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <div className="text-muted-foreground text-xs flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {activity.duration}
                          </div>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap font-semibold text-foreground">
                          ₹{activity.adultPrice.toLocaleString()}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-muted-foreground">
                          ₹{activity.childPrice.toLocaleString()}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2.5 py-1 text-xs font-medium rounded-full ${activity.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-700'
                            }`}>
                            {activity.status}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-right whitespace-nowrap">
                          <button className="text-primary hover:underline font-medium mr-3">Edit</button>
                          <button
                            disabled={deleteMutation.isPending}
                            onClick={() => removeActivity(activity.id)}
                            className="text-muted-foreground hover:text-destructive font-medium disabled:opacity-50"
                          >
                            Delete
                          </button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}

      {/* Add Activity Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm">
          <div className="bg-white dark:bg-slate-900 w-full max-w-lg rounded-xl shadow-2xl overflow-hidden flex flex-col border border-border">
            <div className="flex items-center justify-between p-4 border-b border-border bg-slate-50/50 dark:bg-slate-800/50">
              <h2 className="text-lg font-bold text-foreground">Add New Activity</h2>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-muted-foreground hover:text-foreground transition-colors p-1 rounded-md hover:bg-muted"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <form onSubmit={handleAdd} className="p-5 flex flex-col gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Activity Name *</label>
                <input
                  required
                  type="text"
                  value={newActivity.name}
                  onChange={(e) => setNewActivity({ ...newActivity, name: e.target.value })}
                  placeholder="e.g. Snorkelling at North Bay"
                  className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Location *</label>
                  <div className="relative">
                    <input
                      required
                      type="text"
                      value={newActivity.location}
                      onChange={(e) => setNewActivity({ ...newActivity, location: e.target.value })}
                      placeholder="e.g. Havelock Island"
                      className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                    />
                    <MapPin className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Duration</label>
                  <div className="relative">
                    <input
                      required
                      type="text"
                      value={newActivity.duration}
                      onChange={(e) => setNewActivity({ ...newActivity, duration: e.target.value })}
                      placeholder="e.g. 2 Hours"
                      className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                    />
                    <Clock className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Adult Price (₹)</label>
                  <input
                    required
                    type="number"
                    min="0"
                    value={newActivity.adultPrice}
                    onChange={(e) => setNewActivity({ ...newActivity, adultPrice: Number(e.target.value) })}
                    className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Child Price (₹)</label>
                  <input
                    required
                    type="number"
                    min="0"
                    value={newActivity.childPrice}
                    onChange={(e) => setNewActivity({ ...newActivity, childPrice: Number(e.target.value) })}
                    className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Status</label>
                <select
                  value={newActivity.status}
                  onChange={(e) => setNewActivity({ ...newActivity, status: e.target.value as "ACTIVE" | "INACTIVE" })}
                  className="w-full bg-white dark:bg-slate-950 border border-slate-300 dark:border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary text-foreground"
                >
                  <option value="ACTIVE">Active</option>
                  <option value="INACTIVE">Inactive</option>
                </select>
              </div>

              <div className="pt-4 flex gap-3 mt-2 border-t border-border">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="flex-1 py-2.5 text-sm font-semibold border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 py-2.5 text-sm font-bold bg-primary text-primary-foreground rounded-lg hover:bg-primary-hover transition-colors shadow-sm flex justify-center items-center gap-2"
                >
                  <Plus className="h-4 w-4" /> Save Activity
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      <AlertModal
        isOpen={alertState.isOpen}
        message={alertState.message}
        onClose={() => setAlertState({ isOpen: false, message: "" })}
      />

      {/* Confirm delete dialog */}
      {confirmDeleteId && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <button type="button" className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={() => setConfirmDeleteId(null)} aria-label="Cancel" />
          <div className="relative w-full max-w-sm rounded-lg border border-border bg-white dark:bg-slate-900 shadow-xl p-6 space-y-4">
            <h3 className="font-semibold text-foreground">Remove Activity</h3>
            <p className="text-sm text-muted-foreground">Are you sure you want to delete this activity? This action cannot be undone.</p>
            <div className="flex justify-end gap-2">
              <button type="button" onClick={() => setConfirmDeleteId(null)} className="px-4 py-2 text-sm rounded-md border border-border hover:bg-muted transition-colors">
                Cancel
              </button>
              <button
                type="button"
                onClick={() => void handleConfirmDelete()}
                className="px-4 py-2 text-sm rounded-md bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
              >
                Remove
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
