/**
 * The original 7 event types are per this sprint's brief.
 * INTEGRATION_CONFIG_CHANGED was added for SEC-001 (Integration Vault
 * Hardening) — the vault had zero audit trail for who changed a stored
 * credential or provider status; `details` never includes the secret
 * value itself, only the provider key and which field names changed.
 */
export const AuditEventType = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FAILED_LOGIN: "FAILED_LOGIN",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  PASSWORD_RESET: "PASSWORD_RESET",
  USER_CREATED: "USER_CREATED",
  ROLE_CHANGED: "ROLE_CHANGED",
  INTEGRATION_CONFIG_CHANGED: "INTEGRATION_CONFIG_CHANGED",
  DESTINATION_CREATED: "DESTINATION_CREATED",
  DESTINATION_UPDATED: "DESTINATION_UPDATED",
  DESTINATION_PUBLISHED: "DESTINATION_PUBLISHED",
  DESTINATION_UNPUBLISHED: "DESTINATION_UNPUBLISHED",
  DESTINATION_ARCHIVED: "DESTINATION_ARCHIVED",
  DESTINATION_RESTORED: "DESTINATION_RESTORED",
  DESTINATION_DUPLICATED: "DESTINATION_DUPLICATED",
  INVENTORY_CREATED: "INVENTORY_CREATED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  INVENTORY_PUBLISHED: "INVENTORY_PUBLISHED",
  INVENTORY_UNPUBLISHED: "INVENTORY_UNPUBLISHED",
  INVENTORY_ARCHIVED: "INVENTORY_ARCHIVED",
  INVENTORY_RESTORED: "INVENTORY_RESTORED",
  INVENTORY_DUPLICATED: "INVENTORY_DUPLICATED",
  PACKAGE_CREATED: "PACKAGE_CREATED",
  PACKAGE_UPDATED: "PACKAGE_UPDATED",
  PACKAGE_PUBLISHED: "PACKAGE_PUBLISHED",
  PACKAGE_UNPUBLISHED: "PACKAGE_UNPUBLISHED",
  PACKAGE_ARCHIVED: "PACKAGE_ARCHIVED",
  PACKAGE_RESTORED: "PACKAGE_RESTORED",
  PACKAGE_DUPLICATED: "PACKAGE_DUPLICATED",
  FERRY_RATE_CREATED: "FERRY_RATE_CREATED",
  FERRY_RATE_UPDATED: "FERRY_RATE_UPDATED",
  FERRY_RATE_DELETED: "FERRY_RATE_DELETED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_ARCHIVED: "CUSTOMER_ARCHIVED",
  CUSTOMER_RESTORED: "CUSTOMER_RESTORED",
  ENQUIRY_CREATED: "ENQUIRY_CREATED",
  ENQUIRY_UPDATED: "ENQUIRY_UPDATED",
  ENQUIRY_STATUS_CHANGED: "ENQUIRY_STATUS_CHANGED",
  ENQUIRY_DELETED: "ENQUIRY_DELETED",
  QUOTE_CREATED: "QUOTE_CREATED",
  QUOTE_UPDATED: "QUOTE_UPDATED",
  QUOTE_STATUS_CHANGED: "QUOTE_STATUS_CHANGED",
  QUOTE_DELETED: "QUOTE_DELETED",
} as const;

export type AuditEventType = (typeof AuditEventType)[keyof typeof AuditEventType];

/** actorUserId is who performed the action (null for a pre-auth failed login attempt); targetUserId is who it was done to, when different from the actor (e.g. an admin changing someone else's role). */
export interface AuditLog {
  id: string;
  eventType: AuditEventType;
  actorUserId: string | null;
  targetUserId: string | null;
  details: Record<string, unknown> | null;
  ipAddress: string | null;
  occurredAt: string;
}
